# IMPORT THE RANDOM MODULE

# WELCOME THE USER AND DISPLAY INSTRUCTIONS

# CREATE A VARIABLE TO STORE THE RANDOM NUMBER FOR THE USER TO GUESS

# CREATE A VARIABLE TO STORE THE USER'S GUESS

# CREATE A VARIABLE TO STORE THE NUMBER OF ATTEMPTS THE USER STARTS WITH, DEPENDENT ON THE DIFFICULTY

# CREATE A FUNCTION FOR USER TO CHOOSE A DIFFICULTY LEVEL

# CREATE A FUNCTION TO CHECK THE USERS GUESS AGAINST THE ANSWER

# CREATE A WHILE LOOP TO KEEP THE GAME GOING UNTIL THE USER GUESSES THE CORRECT ANSWER

